# -----------------------------------------------------------------
#  Spring Boot Server Configuration
# -----------------------------------------------------------------
server:
  port: 8080 # This is the default, but good to define explicitly

# -----------------------------------------------------------------
#  Database Connection (DataSource)
# -----------------------------------------------------------------
spring:
  docker:
    compose:
      enabled: false
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/pendragon?authSource=admin